#!/usr/bin/env python3
import configparser
import argparse
from dftpy.interface import OptimizeDensityConf
from dftpy.config import OptionFormat, PrintConf, ReadConf


def RunJob():
    parser = argparse.ArgumentParser(description='Process task')

    parser.add_argument('-i', '--ini', '--input', dest='input', type=str, action='store',
            default='config.ini', help='input file (default: config.ini)')

    args = parser.parse_args()
    conf = ReadConf(args.input)
    config = OptionFormat(conf)
    PrintConf(config)
    results = OptimizeDensityConf(config)
    # results = OptimizeDensityConf(args.input)


if __name__ == "__main__":
    RunJob()
